// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_MsgHeartbeatReq MessageType = 0
	MessageType_MsgHeartbeatRsp MessageType = 1
	MessageType_MsgVoteReq      MessageType = 2
	MessageType_MsgVoteRsp      MessageType = 3
)

var MessageType_name = map[int32]string{
	0: "MsgHeartbeatReq",
	1: "MsgHeartbeatRsp",
	2: "MsgVoteReq",
	3: "MsgVoteRsp",
}
var MessageType_value = map[string]int32{
	"MsgHeartbeatReq": 0,
	"MsgHeartbeatRsp": 1,
	"MsgVoteReq":      2,
	"MsgVoteRsp":      3,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_raft_16e55bffb4054d9a, []int{0}
}

type Entry struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_16e55bffb4054d9a, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Message struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.MessageType" json:"type,omitempty"`
	Term                 uint64      `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             uint64      `protobuf:"varint,3,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	From                 uint64      `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   uint64      `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`
	LastLogIndex         uint64      `protobuf:"varint,6,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm          uint64      `protobuf:"varint,7,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	Success              bool        `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode              uint64      `protobuf:"varint,9,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_16e55bffb4054d9a, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_MsgHeartbeatReq
}

func (m *Message) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Message) GetLeaderId() uint64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *Message) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Message) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Message) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *Message) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *Message) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Message) GetErrCode() uint64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterEnum("pb.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_raft_16e55bffb4054d9a) }

var fileDescriptor_raft_16e55bffb4054d9a = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x6c, 0x93, 0x26, 0xef, 0x54, 0xd2, 0xb0, 0x7a, 0x58, 0x3c, 0x85, 0x78, 0x29,
	0x1e, 0x02, 0xea, 0x47, 0x10, 0xc1, 0x82, 0xb9, 0x84, 0xa2, 0xe7, 0x4d, 0x33, 0x0d, 0x42, 0xdb,
	0x5d, 0x77, 0x47, 0x30, 0xdf, 0xdd, 0x83, 0x64, 0xfa, 0x87, 0x88, 0xb7, 0xf9, 0xfd, 0x9e, 0x67,
	0x26, 0x09, 0x01, 0x70, 0x7a, 0x43, 0xa5, 0x75, 0x86, 0x8c, 0x14, 0xb6, 0x29, 0xee, 0x20, 0x7a,
	0xda, 0x93, 0xeb, 0xa5, 0x84, 0x90, 0xd0, 0xed, 0x54, 0x90, 0x07, 0x8b, 0xb0, 0xe6, 0x59, 0x5e,
	0x41, 0xf4, 0xbe, 0x6f, 0xf1, 0x4b, 0x09, 0x96, 0x07, 0x28, 0xbe, 0x03, 0x88, 0x2b, 0xf4, 0x5e,
	0x77, 0x28, 0x6f, 0x20, 0xa4, 0xde, 0x22, 0x6f, 0xa5, 0xf7, 0xf3, 0xd2, 0x36, 0xe5, 0x31, 0x5a,
	0xf5, 0x16, 0x6b, 0x0e, 0xcf, 0xa7, 0xc5, 0xe8, 0xf4, 0x35, 0x24, 0x5b, 0xd4, 0x2d, 0xba, 0x65,
	0xab, 0x26, 0xec, 0xcf, 0x3c, 0xf4, 0x37, 0xce, 0xec, 0x54, 0x78, 0xe8, 0x0f, 0xb3, 0x4c, 0x41,
	0x90, 0x51, 0x11, 0x1b, 0x41, 0x46, 0x16, 0x70, 0xb1, 0xd5, 0x9e, 0x5e, 0x4c, 0xb7, 0xe4, 0x37,
	0x9c, 0x72, 0xf2, 0xcb, 0xc9, 0x1c, 0x66, 0x47, 0x5e, 0x0d, 0x8f, 0x8f, 0xb9, 0x32, 0x56, 0x52,
	0x41, 0xec, 0x3f, 0xd7, 0x6b, 0xf4, 0x5e, 0x25, 0x79, 0xb0, 0x48, 0xea, 0x13, 0x0e, 0x09, 0x3a,
	0xf7, 0x68, 0x5a, 0x54, 0xff, 0x79, 0xef, 0x84, 0xb7, 0x6f, 0x30, 0x1b, 0x7d, 0xa2, 0xbc, 0x84,
	0x79, 0xe5, 0xbb, 0x67, 0xd4, 0x8e, 0x1a, 0xd4, 0x54, 0xe3, 0x47, 0xf6, 0xef, 0x8f, 0xf4, 0x36,
	0x0b, 0x64, 0x0a, 0x50, 0xf9, 0xee, 0xd5, 0x10, 0x0e, 0x25, 0x31, 0x66, 0x6f, 0xb3, 0x49, 0x33,
	0xe5, 0xbf, 0xf2, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x16, 0x66, 0x12, 0x69, 0xa3, 0x01, 0x00,
	0x00,
}
